language: php

php:
- 7.1
- 7.2
- 7.3
- 7.4

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --prefer-dist --no-interaction

before_script:
  - mkdir -p build/logs
  - ls -al

script:
  - phpunit --verbose --coverage-clover build/logs/clover.xml
  - ./vendor/bin/phpstan analyse -c phpstan.neon

after_success:
  - travis_retry php vendor/bin/php-coveralls -v

branches:
  only:
   - master